### PR TITLE
Increase upper bound on `pipes` dependency

### PR DESCRIPTION
**Pull request by Gabriel439**

### CODE REVIEW

**Comment by k0001** [comment]
Thanks! I'm away from the computer now, so I'll upload this change to hackage later. And do the same in my other packages.

**Comment by chrisdone** [comment]
@k0001 Bump. Is it possible to pop this on Hackage? 👍

**Comment by k0001** [comment]
Uploaded as `pipes-attoparsec-0.5.1.4`

**Comment by chrisdone** [comment]
Thanks!

**Pull request merged**
